name: first
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  flutter_typeahead: ^4.0.0  # For search bar with autocomplete
  speech_to_text: ^6.6.2     # For voice functionality
  local_auth: ^2.3.0
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/ # Add your image path here
